export default {
  login: "auth/login",
  createUser: "auth/register",
  changePassword: "auth/changePassword",
  users: "users",
  rmaDictionaryDamageTypes: "rma/dictionary/getDict/damages",
  rmaDictionaryAccessoriesTypes: "rma/dictionary/getDict/accessories",
  rmaDictionaryStatusesTypes: "rma/dictionary/getDict/statuses",
  rmaDictionaryResultTypes: "rma/dictionary/getDict/results",
  rmaAccessories: "rma/accessories",
  rmaWaybills: "rma/waybills",
  rmaCreate: "rma/create",
  rmaPage: "rma/details",
  rmaChangeStatus: "rma/changeState",
  rmaEdit: "rma",
  rmaRegisterItem: "rma/register",
  rmaList: "rma",
  warehouseCreateItem: "warehouse/items",
  warehouseShelves: "warehouse/shelve",
  warehouseItems: "warehouse/items",
  warehouseChangeShelve: "warehouse/items/changeshelve",
  collectPackages: "warehouse/collect",
  collectPackagesAdd: "warehouse/collect/add",
  collectPackageItems: "warehouse/collect/items",
  tasks: "warehouse/tasks",
  logs: "logs",
};
